### ISSUE TITLE
USB 에뮬레이터용 Assetto Corsa 설정 자동화

### ISSUE THREAD

**Issue by YuujinHwang** [3secondz-lab/hitchhiker#31]
설정 파일을 통하여 별도의 과정 없이 인식시키는 것을 목표로 합니다.
가능한 방법들이 있을까요?

**Comment by jphil3sec** [comment]
게임 내 설정 과정을 자동으로 하는 것 말씀하시는거죠?
\Documents\Assetto Corsa\cfg\controllers
여기에 ini 파일 형태로 설정이 저장되는데 여기 파일을 수정하는 방법으로 가능할 것 같기도 합니다

**Comment by jphil3sec** [comment]
\Documents\Assetto Corsa\cfg\controllers
여기는 preset이랑 사용자가 저장한 내용이고

현재 사용되는 설정 값은 이 파일에 저장되는 것 확인했습니다
\Documents\Assetto Corsa\cfg\controls.ini
