### ISSUE TITLE
시뮬레이션 데이터 API와 컨트롤러 topic 분리

### ISSUE THREAD

**Issue by YuujinHwang** [3secondz-lab/hitchhiker#36]
현재 assetto_corsa 내부에

- 소켓통신
- 컨트롤러
- 조이스틱 인풋

부분이 다 합쳐져 있습니다만,

(시뮬레이션 데이터 인풋) -> (MATLAB 컨트롤러) -> (컨트롤 명령 액추에이션)

하는 3단계로 나누어야 할 것 같습니다.!

컨트롤 하는 부분이 매 게임 및 차량마다 달라져야 할 경우 (일반적으로 그럴 것 같습니다.)

(데이터 입/출 부분) <-> 나머지 노드 로 2종류로만 분할해도 될 것 같습니다.

**Comment by YuujinHwang** [comment]
https://github.com/UnlicensedGarage/openpilot/blob/release2/cereal/car.capnp
https://github.com/UnlicensedGarage/openpilot/blob/release2/cereal/log.capnp

openpilot의 메시지 구조입니다.

**Comment by zzangjinsun** [comment]
Simulation data message 정의에는 두 가지 방법이 있을 것 같습니다.

1. 범용 Message 를 정의하여 모든 Simulation에서 공유하도록 설계 - 이 경우 모든 Field를 쓰지 않기 때문에 항상 overhead 발생이 예상됨. 다만 Subscription이 쉬워짐

2. 범용 Subscriber를 정의하여 다양한 message 형식에 대응하도록 설계 - 이 경우 subscriber가 새로운 message가 추가 될 때 마다 수정되어야 하는 불편함이 있음. 다만 Simulation publish가 쉬워짐.

어떤 경우를 선택하던 우선은 다양한 Simulator 및 실제 센서 데이터에서 가져다 쓸 데이터 list를 먼저 정의하는 것이 좋을 것 같습니다. 현재는 AC에서 오는 데이터 전부를 보내고 있기 때문에...

**Comment by zzangjinsun** [comment]
우선 Joystick Controller 패키지는 분리해 두었습니다.
